


// tag::DE[]
=== {learning-goals}

[[LZ-6-1]]
==== LZ 6-1: Anwendbarkeit und Einsatzgebiete von Behavior-Driven Development (BDD) kennen

* Wissen, dass BDD <<smart-bdd>> aus Ansätzen und Technologien wie TDD (Test-Driven Development) und ATDD (Acceptance-Test-Driven Development) entstanden ist
* Wissen, dass es verschiedene Möglichkeiten gibt, Anforderungen zu präzisieren
** Zustands- oder Aktivitätsmodelle
** Given-When-Then-Szenarien
* Wissen, dass BDD für eine große Bandbreite von IT-Systemtypen anwendbar ist, z.B. Informationssysteme, Business-Intelligence-Systeme, mobile Apps


[[LZ-6-2]]
==== LZ 6-2: Prinzipien von Behaviour-Driven Development (BDD) verstehen

* Wissen, dass BDD eine kollaborative Praktik zur Entdeckung von Anforderungen ist, die Gespräche über konkrete Beispiele nutzt, um ein gemeinsames Verständnis der Anforderungen aufzubauen
* Wissen, dass kollaborative Workshops und Diskussionsformate wie Three Amigo Sessions (TAS) <<smart-amigo>> helfen, korrekte Anforderungen zu erhalten. In einer TAS arbeiten die drei Rollen „Product Owner" (oder Business Analyst), „Entwickler:in" und „Tester:in" gemeinsam an der Entdeckung von Anforderungen.
* Wissen, dass konkrete Beispiele gut geeignet sind, die Problemdomäne zu erkunden, und eine Grundlage für Akzeptanztests bieten. Example Mapping <<wynn>> hilft, Regeln und offene Fragen zu finden und neue Stories zu identifizieren.
* Wissen, dass BDD Benutzeranforderungen in Features beschreibt, Features in Stories herunterbricht und die Stories in (ausführbare) Beispiele


[[LZ-6-3]]
==== LZ 6-3: Gherkin und Cucumber als Beispiele für BDD kennen

* Die Given-When-Then-Syntax (GWT) kennen, wie Gherkin sie vorschlägt
* Wissen, dass Given-When-Then-basierte Formulierungen von Anforderungen die Testautomatisierung erleichtern
* Wissen, dass mehrere Werkzeuge existieren, um Given-When-Then-Verhaltensspezifikationen auf den Quellcode des Systems abzubilden (z.B. Cucumber, RSpec, SpecFlow, GivWenZen)
* Optional Beispiele für GWT-Spezifikationen mit dem zugehörigen Glue Code für die automatische Ausführung kennen

// end::DE[]

// tag::EN[]
=== {learning-goals}



[[LG-6-1]]
==== LG 6-1: Knowing about the applicability and application domains for Behavior-Driven Development (BDD)

* Know that BDD <<smart-bdd>> originated from approaches and technologies like TDD (test-driven development) and ATDD (acceptance-test-driven development).
* Know that various options exist to add precision to requirements
** State models or activity models
** given-when-then scenarios
* Know that BDD is applicable for a broad range of IT-system types, e.g. information systems, business intelligence systems, mobile apps


[[LG-6-2]]
==== LG 6-2: Understanding principles of Behaviour-Driven Development (BDD)

* Know that BDD is a collaborative requirements discovery practice that uses conversations around concrete examples to build a shared understanding of requirements.
* Know that collaborative workshops and discussion formats, like Three Amigo Sessions (TAS) <<smart-amigo>>, help in getting correct  requirements.  In a TAS, the three roles "product owner" (or business analyse), "developer" and "tester" collaborate in discovering requirements.
* Know that concrete examples are a suitable way to help explore the problem domain, and they provide a basis for acceptance tests. Example mapping <<wynn>> helps to find rules, open questions and identify new stories.
* Know that BDD explains user requirements in features, breaks features down into stories and the stories into (executable) examples.


[[LG-6-3]]
==== LG 6-3: Knowing Gherkin and Cucumber as examples for BDD

* Know the Given-When-Then (GWT) syntax as proposed by Gherkin.
* Know that Given-When-Then based formulations of requirements facilitate test automation.
* Know that several tools exist to map Given-When-Then behavior specifications to the systems' source code (e.g. Cucumber, RSpec, SpecFlow, GivWenZen).
* Optionally know examples of GWT specifications with the appropriate glue code for automatic execution.

// end::EN[]

