language: java
install: true
jdk:
- oraclejdk11
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew buildDocs publish --info --stacktrace"
- ls -laR ./build | grep -v .git
deploy:
  provider: releases
  on:
    branch: master
    tags: true
  file_glob: true
  file:
  - build/req4arc-curriculum-en*
  - build/images
  skip_cleanup: true
  overwrite: true
env:
  global:
    secure: k8lHVIdBWyPeGTnaxokW2dwBRTTqunhyhS/QG1Ow0DQLCk2eMoWqPo1r74ehYfCKDennpoG4ZON20k//wzWw/G2xb9zNWpobCN3w6Fx6OiH048Lsjr1QrB1Vu8UySLMDfVJ0eIReU3lckleRM1KRZP9wjtIyVqiMXwMIaEKeU5YayknALT2hALkyeU9m1lK98irTSQqARX72yKZpopsJo7EsonoPlDRAodOGBNMzvy57ZIvd7wP4xpF3lL88kswGDmw9FtKCfr3MzVuwVJCCpmhuJikhqzmZ+LRQtuyGyBuxqGZWJohSJZf9xe3VOTZf7xM53lRQ1D6Ny+92iCF8nxeoVEQwueJIbcS1hslZl2mVV62L1qAByb7Bq8HvM8B3eR4sjmvoPa/8FD1UOEtVJVWWC7lS01th6/AbkH4TgWhvNI15A5ApX3ZvmmwMBOoSGH4Bzb/SjOmlFMQAX/+6OejEMzmPgvLj8w49DO+B8t2bnXVHLmYQ8xZjc2svxgZdfW8eue8aBsh5Z8vi74Y4rLPjxG+OiGHg79Ip7Kcx+GkiV5DIu5YTlTgSjwh9FTaKR88ap0YcHKsfDgcEJz1JJJ9lw/aqHQsI17LlEW0OPywU7Jn5+wwTAGVWz4uoiYscexptkjkW6xl4ZV4jdzhXf2rffcRZXOzs4xTCObdwThI=
notifications:
  slack: starketeam42
  secure: La6Z8Le8k0jWGTtjS6ZzA+K0KAoZhoXSwhqGrhZgFESGgBS5CtvyHN49P60jGiYazJ7vmv/K9F7Ic5uVEFsRf+F6Ue6laceXcPh+ToiefKbvkkQjQ2Qag/QFEGhiITYpb/0yC1WsUdUuinxZay6ScwvCZAISZh90bBp84qGDsdwXyx/jkMKsl+DGgAsQzTVlGS20Rt0klEN5bZ7SNDD44JhGMeQjX2s7Qe5O90/F1eUAgpL7PoTfPyTOXC2/z3jLWMeqhT2UNdyUMdjV+QHXEgNmoGjS66EvKNGXWlQWwiATUM0cFRedI2dWsgM0isylglAEGjm/RWZZxIqMValVKfrd3vjFlhQD3Vz78qYIKZgapR3XAKRlE/eJii/VJTUmpYVuexnj0lDhRAdTPq9XAXIXbT4XpMNfEUmNhN97aNa3ZZolli/amWD+qMmwoLrnn3MCcDmaispCt6Ma9sKpqcauYhdEg+mvtMNO6W7xlP2ODixWHzSbrJpaLtU6R69JeJO/1MamnebDm4BadVMu5e1cym0U5OBSw9HrIAdqg7/VQdVNV1lrAOiTP9PMI9oImjDVixhrGYDgGS9/bt0jxLGtThPC8qSofzfxHmCSj45B4gvKB67X5z4MaeeHkFjnrRthvDFp/CTrSgk3HTXEFS7D41NSfWjfjJdzzg5UIVc=
