// tag::FEEDBACK[]
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
[[LG-2-1]]
===== LG 2-1: Verstehen der Notwendigkeit einiger (begrenzter) Vorleistungen

* Verstehen, dass selbst bei iterativer Entwicklung einige Vorleistungen erforderlich sind.

* Wissen, dass explizite Kenntnisse über Visionen, Ziele und relevante Stakeholder erforderlich sind, damit das Entwicklungsteam fundierte Entscheidungen über die Systemarchitektur treffen kann.
* Verstehen, dass eine Vereinbarung über Umfang und Kontext erforderlich ist, insbesondere über die Schnittstellen zwischen Umfang und Kontext (d.h. die externen Schnittstellen des Produkts).

[[LG-2-2]]
===== LG 2-2: Verständnis für die Notwendigkeit von (high-level) Visionen und Geschäftszielen

* Verstehen, dass Visionen oder Geschäftsziele Ihre höchsten Anforderungen sind, d.h. die Anforderungen, die (hoffentlich) während eines Projekts nicht geändert werden.
* Verstehen, dass Visionen und Ziele quantifiziert und messbar gemacht werden sollten, um den Erfolg in Bezug auf den Geschäftswert überprüfen zu können.

[[LG-2-3]]
===== LG 2-3: Verschiedene Möglichkeiten und Notationen, um Visionen und Unternehmensziele auszudrücken

* verschiedene Möglichkeiten kennen, um Vision und Ziele zu definieren (explizite Zielerklärungen, Wertversprechen für verschiedene Stakeholder, Visionsfeld, "Neuigkeiten aus der Zukunft")
* Mnemotechnik für Visionen oder Geschäftszielsetzungen kennen (SMART, PAM)

[[LG-2-4]]
===== LG 2-4: Die Bedeutung der verschiedenen Stakeholder und ihr Einfluss auf das Produkt oder System

* Wissen, dass die Stakeholder die wichtigsten Quellen für Anforderungen sind.
* Verstehen, dass fehlende Stakeholder fehlende Anforderungen bedeuten können.
* Verstehen, dass Architekten sich bewusst sein sollten, dass die Stakeholder auf spezifische, angemessene Weise angesprochen werden müssen.

[[LG-2-5]]
===== LG 2-5: Unterschiedliche Bedürfnisse und Werte der verschiedenen Stakeholder ("Value Propositions")

* Verstehen, dass verschiedene Interessengruppen unterschiedliche Bedürfnisse haben und unterschiedliche Meinungen darüber haben können, was an einem Produkt wertvoll ist.
* Wissen, dass eine priorisierte Stakeholderliste hilft, Anforderungen nach Geschäftswert zu priorisieren
* Wissen, dass Architekten mit Zielkonflikten zwischen den Bedürfnissen der Stakeholder umgehen müssen

[[LG-2-6]]
===== LG 2-6: Umfang und Abgrenzung des Kontexts des Systems

* Unterscheidung zwischen Geschäfts- und Produktumfang kennen
* Wissen über die Bedeutung externer Schnittstellen
* Unterscheiden zwischen verschiedenen Ebenen der Externalität (extern zum System, extern zur Geschäftseinheit, extern zum Unternehmen)
* verschiedene Möglichkeiten und Notationen kennen, um Umfang und Kontext auszudrücken, z.B. Kontextdiagramme


// end::DE[]

// tag::EN[]
[[LG-2-1]]
==== LG 2-1: Understanding the need for some (limited) upfront activities

* Understand that even with iterative development some upfront activities are necessary.

* Know that explicit knowledge of visions, goals and relevant stakeholders are required so that the development team can take informed decisions about the systems’ architecture.
* Understand that an agreement about scope and context is required, especially about the interfaces between scope and context (i.e. the external interfaces of the product).

[[LG-2-2]]
==== LG 2-2: Understanding the need for (high level) vision and business goals

* Understand that visions or business goals are your highest level requirements, i.e. those requirements that are (hopefully) not changed during a project
* Understand that visions and goals should be quantified and made measurable to be able to check success in terms of business value.

[[LG-2-3]]
==== LG 2-3: Different options and notations for expressing visions and business goals

* Know various ways to define vision and goals (explicit goal statements, value propositions for different stakeholders, vision box, "news from the future")
* Know mnemonics for vision or business goal statements (SMART, PAM)

[[LG-2-4]]
==== LG 2-4: The importance of different stakeholders and their influence on the product or system

* Know that stakeholders are the most important sources of requirements.
* Understand that missing stakeholders may mean missing requirements.
* Understand that architects should be aware that stakeholders need to be addressed in specific, adequate ways.

[[LG-2-5]]
==== LG 2-5: Different needs and values of different stakeholders  ("value propositions")

* Understand that different stakeholders will have different needs and may differ in their opinions what is valuable in a product
* Know that a prioritized stakeholder list helps to prioritize requirements by business value
* Know that architects have to handle goal conflicts between stakeholder's needs

[[LG-2-6]]
==== LG 2-6: Scoping and delimiting the context of the system

* Distinguish between business and product scope
* Know about the importance of external interfaces
* Distinguish between various levels of externality (external to the system, external to the business unit, external to the enterprise)
* Know different options and notations for expressing scope and context, i.e. context diagrams


// end::EN[]

// tag::REMARK[]
// end::REMARK[]
