

// tag::DE[]

=== {learning-goals}

[[LZ-8-1]]
==== LZ 8-1: Verschiedene Arten von Business Value verstehen

* Verstehen, dass verschiedene Stakeholder unterschiedlichen Wert in Anforderungen sehen können.
Manche interessieren sich für kurzfristigen Umsatz, andere für bessere Kundenzufriedenheit oder schnelle Time-to-Market.
Wieder andere wollen das Risiko für die restliche Entwicklung reduzieren oder eine Plattform für langfristige Kosteneinsparungen schaffen.
* Verschiedene Methoden kennen, um Wert auszudrücken, z.B. MoSCoW-Priorisierung, definierte Wertebereiche, lineare Sortierung aller Anforderungen, gewichtete Faktorenmethoden, Cost of Delay, ...


[[LZ-8-2]]
==== LZ 8-2: Anforderungen nach Business Value ordnen

* Verschiedene Strategien für Ordnung und Priorisierung kennen, z.B. Weighted Shortest Job First (WSJF), Defer Risk, Risk First, ...
* Wissen, wie man beim Ordnen mit Abhängigkeiten zwischen Anforderungen umgeht
* Mechanismen kennen, um Anforderungen zu zerlegen und so Abhängigkeiten zu vermeiden

[[LZ-8-3]]
==== LZ 8-3: Anforderungen schätzen

* Die Notwendigkeit verstehen, Anforderungen zu schätzen – auch als Indikator, größere Anforderungen zu verfeinern und zu zerlegen, wenn sie sich noch nicht gut genug schätzen lassen
* Den Unterschied zwischen absoluten Schätzungen (in Personentagen, Kosten, ...) und relativen Schätzungen (z.B. Story Points) verstehen
* Vor- und Nachteile absoluter und relativer Schätzungen kennen
* Einige relative Schätztechniken kennen, etwa T-Shirt-Sizing und Planning Poker (mit Fibonacci-Werten)
* Verschiedene Schätztechniken kennen, z.B. Function Points, Story Points, Affinity Estimation, Wall Estimation etc.


// end::DE[]

// tag::EN[]

=== {learning-goals}

[[LG-8-1]]
==== LG 8-1: Understanding different kinds of business value

* Understand that different stakeholders may see different value in requirements.
Some of them may be interested in short turn revenue, others in improvement of customer satisfaction, or quick time-to-market.
Others might want to reduce the risk for the rest of the development, or create a platform for longer term cost savings.
* Know different methods for expressing value, e.g. MoSCoW-prioritization, defined ranges of values, linear sorting of all requirements, weighted factor methods, cost of delay, ...


[[LG-8-2]]
==== LG 8-2: Ordering requirements by business value

* Know different strategies for ordering and prioritization, e.g. weighted shortest job first (WSJF), defer risk, risk-first ...
* Know how to handle dependencies between requirements when ordering requirements
* Know mechanism to split requirements in order to avoid dependencies

[[LG-8-3]]
==== LG 8-3: Estimating requirements

* Understand the need for estimating requirements, also as an indicator to potentially refine and decompose larger requirements when they cannot be estimated well enough yet.
* Understand the difference between absolute estimates (in person days, costs, ...) versus relative estimates (e.g. story points)
* Know advantages and disadvantages of absolute and relative estimates
* Know some relative estimation techniques like T-Shirt-sizing, Planning Poker (with Fibonacci values)
* Know different estimation techniques, e.g. function points, story points, affinity estimation, wall estimation, etc.


// end::EN[]
