

// tag::DE[]

=== {learning-goals}

[[LZ-8-1]]
==== LZ 8-1: Verschiedene Arten von Business Value verstehen

* Verstehen, dass verschiedene Stakeholder unterschiedlichen Wert in Anforderungen sehen können.
Manche interessieren sich für kurzfristigen Umsatz, andere für bessere Kundenzufriedenheit oder schnelle Time-to-Market.
Wieder andere wollen das Risiko für die restliche Entwicklung reduzieren oder eine Plattform für langfristige Kosteneinsparungen schaffen. <<mcgreal>>
* Verschiedene Methoden kennen, um Wert auszudrücken, z.B. MoSCoW-Priorisierung <<clegg>> <<moscow>>, definierte Wertebereiche, lineare Sortierung aller Anforderungen, gewichtete Faktorenmethoden, Cost of Delay, ...


[[LZ-8-2]]
==== LZ 8-2: Anforderungen nach Business Value ordnen

* Verschiedene Strategien für Ordnung und Priorisierung kennen, z.B. Weighted Shortest Job First (WSJF), Defer Risk, Risk First, ...
* Wissen, wie man beim Ordnen mit Abhängigkeiten zwischen Anforderungen umgeht
* Mechanismen kennen, um Anforderungen zu zerlegen und so Abhängigkeiten zu vermeiden

[[LZ-8-3]]
==== LZ 8-3: Anforderungen schätzen

Softwarearchitekt:innen verstehen die Notwendigkeit, Anforderungen zu schätzen, auch als Indikator, größere Anforderungen zu verfeinern und zu zerlegen, wenn sie sich noch nicht gut genug schätzen lassen.

Sie kennen:

* den Unterschied zwischen absoluten Schätzungen (z.B. Personentage, Kosten, oder die klassische, formelbasierte Function-Point-Methode <<function-points>> als Gegenstück zu relativen Verfahren) und relativen Schätzungen (z.B. Story Points).
* Vor- und Nachteile absoluter und relativer Schätzungen
* Einige relative Schätztechniken, etwa T-Shirt-Sizing, Affinity Estimation und Planning Poker (mit Fibonacci-Werten)


// end::DE[]

// tag::EN[]

=== {learning-goals}

[[LG-8-1]]
==== LG 8-1: Understanding different kinds of business value

* Understand that different stakeholders may see different value in requirements.
Some of them may be interested in short turn revenue, others in improvement of customer satisfaction, or quick time-to-market.
Others might want to reduce the risk for the rest of the development, or create a platform for longer term cost savings. <<mcgreal>>
* Know different methods for expressing value, e.g. MoSCoW-prioritization <<clegg>> <<moscow>>, defined ranges of values, linear sorting of all requirements, weighted factor methods, cost of delay, ...


[[LG-8-2]]
==== LG 8-2: Ordering requirements by business value

* Know different strategies for ordering and prioritization, e.g. weighted shortest job first (WSJF), defer risk, risk-first ...
* Know how to handle dependencies between requirements when ordering requirements
* Know mechanism to split requirements in order to avoid dependencies

[[LG-8-3]]
==== LG 8-3: Estimating requirements

Software architects understand the need to estimate requirements, also as an indicator to potentially refine and decompose larger requirements when they cannot be estimated well enough yet.

They know:

* the difference between absolute estimates (e.g. person days, costs, or the classical, formula-based function point method <<function-points>> as the counterpart to relative approaches) and relative estimates (e.g. story points).
* advantages and disadvantages of absolute and relative estimates
* some relative estimation techniques, e.g. T-Shirt-sizing, affinity estimation and Planning Poker (with Fibonacci values)


// end::EN[]
