

// tag::DE[]

|===
| Unterricht: 45 Min. | Übungen: 60 Min.
|===

Im Gegensatz zum Wasserfallmodell mit expliziten Phasen für Requirements Engineering und System-/Softwarearchitektur streben alle modernen Methoden eine sehr enge Zusammenarbeit zwischen Architekt:innen und allen für Requirements Engineering verantwortlichen Rollen an.
Beispiele für solche Prozesse sind Design Thinking (<<gerstbach>>), Lean Startup (<<ries>>), Design Sprints (<<banfield>>) und viele Skalierungsframeworks der agilen Welt.

Architekt:innen sollten außerdem unterschiedliche Wege kennen, Anforderungen festzuhalten und zu dokumentieren – vom Pflegen eines Product Backlogs bis zum Erstellen von Anforderungsdokumenten – sowie die Beziehung solcher Anforderungsdokumente zur Architekturdokumentation.

=== Begriffe und Konzepte

Design Thinking (<<gerstbach>>), Design Sprint (<<banfield>>), Lean Startup (<<ries>>), Three Amigo Sessions (<<dinwiddie>>), Twin-Peaks-Modell (<<nuseibeh>>), Discover-to-Deliver (<<gottesdiener-12>>), Anforderungsdokumentation, Traceability

// end::DE[]

// tag::EN[]

|===
| Teaching: 45 min | Exercises: 60 min
|===

In contrast to the waterfall model with explicit phases for requirements engineering and system/software architecture development all modern methods strive for a very close cooperation between architects and any role that is responsible for requirements engineering.
Examples for such processes include design thinking (<<gerstbach>>), lean startup (<<ries>>), design sprints (<<banfield>>) and many of the scaling frameworks in the agile world.

Architects should also understand different ways to capture and document requirements, from managing a product backlog to creating requirements documents - and the relationship of such requirements documents to architecture documentation.

=== Terms and concepts

Design Thinking (<<gerstbach>>), Design Sprint (<<banfield>>), Lean Startup (<<ries>>), Three Amigo Sessions (<<dinwiddie>>), Twin Peaks Model (<<nuseibeh>>), Discover-to-Deliver (<<gottesdiener-12>>), Requirements Documentation, Traceability


// end::EN[]


