

// tag::DE[]

=== {learning-goals}

[[LZ-2-1]]
==== LZ 2-1: Die Zusammenarbeit zwischen Architekt:innen und anderen Rollen rund um Anforderungen verstehen

* Verstehen, dass iterative Systementwicklung alle am Entwicklungsprozess beteiligten Rollen einbezieht
* Wissen, dass Architekt:innen laufend mit Business Analysts und Anforderungsverantwortlichen sowie mit Entwickler:innen und Tester:innen interagieren <<robertson-19>>

[[LZ-2-2]]
==== LZ 2-2: Kooperative Ansätze der Produktentwicklung kennen

* Die Grundideen kooperativer Ansätze kennen, etwa _Discover to Deliver_ <<gottesdiener-12>>, Design Thinking <<gerstbach>>, Lean Startup <<ries>>, Design Sprints <<banfield>>, Twin-Peaks-Modell (<<nuseibeh>>)
* Three Amigo Sessions (TAS) <<dinwiddie>> <<smart-amigo>> als kollaboratives Format kennen: Die drei Rollen „Product Owner" (oder Business Analyst), „Entwickler:in" und „Tester:in" arbeiten darin gemeinsam an der Entdeckung von Anforderungen (vgl. <<LZ-4-11>>, <<LZ-6-2>>)
* Verstehen, wie sich solche iterativen Ansätze auf größere Systeme skalieren lassen, an denen mehrere – möglicherweise geografisch verteilte – Entwicklungsteams beteiligt sind


[[LZ-2-3]]
==== LZ 2-3: Anforderungsdokumentation verstehen

* Wissen, dass in formaleren Situationen schriftliche Anforderungsspezifikationen unverzichtbar sind
* Wissen, dass mündliche Kommunikation (_reden und diskutieren_) oft wirksamer ist als Schreiben
* Die Balance zwischen Schreiben und Reden verstehen (Anforderungsspezifikation versus Story Cards)


[[LZ-2-4]]
==== LZ 2-4: Traceability von Anforderungen zu anderen Artefakten verstehen

* Wissen, was _Tracing_ von Anforderungen zu Architektur, Quellcode, Tests und technischer Dokumentation bedeutet
* Verstehen, dass Anforderungs-Tracing zeitaufwendig ist und passende Werkzeugunterstützung erfordert
* Verstehen, dass Anforderungs-Tracing manchmal verpflichtend ist, z.B. bei sicherheitskritischen Systemen

// end::DE[]

// tag::EN[]

=== {learning-goals}

[[LG-2-1]]
==== LG 2-1: Understand the cooperation between architects and other roles concerning requirements

* Understand that iterative system development includes all roles involved in the development process
* Know that architects constantly interact with business analysts and requirements persons, as well as developers and testers <<robertson-19>>

[[LG-2-2]]
==== LG 2-2: Know cooperative approaches to product development

* Know the basic ideas of cooperative approaches like _Discover to Deliver_ <<gottesdiener-12>>, Design Thinking <<gerstbach>>, Lean Startup <<ries>>, Design Sprints <<banfield>>, Twin Peaks Model (<<nuseibeh>>)
* Know Three Amigo Sessions (TAS) <<dinwiddie>> <<smart-amigo>> as a collaborative format: the three roles "product owner" (or business analyst), "developer" and "tester" work together to discover requirements (see <<LG-4-11>>, <<LG-6-2>>)
* Understand how such iterative approaches can be scaled to larger systems, that involve more than one development team, potentially geographically distributed.


[[LG-2-3]]
==== LG 2-3: Understand requirements documentation

* Know that in more formal situations written requirements specifications are essential
* Know that oral communication (_talking and discussing_) is often more effective than writing
* Understand the balance between writing and talking (requirements specification versus story cards)


[[LG-2-4]]
==== LG 2-4: Understand traceability from requirements to other artifacts

* Know what requirements _tracing_ to architecture, source code, test, technical documentation means
* Understand that requirements tracing is time-consuming and requires appropriate tool support
* Understand that requirements tracing is sometimes mandatory, e.g. for safety-critical systems.

// end::EN[]
