// tag::FEEDBACK[]
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

[LG-6-1]]
=== {learning-goals}

===== LG 6-1: Verstehen verschiedener Arten von Geschäftswerten

* Verstehen, dass verschiedene Stakeholder unterschiedlichen Wert in den Anforderungen sehen können.
Einige von ihnen können an kurzfristigen Einnahmen, andere an der Verbesserung der Kundenzufriedenheit oder einer schnellen Markteinführung interessiert sein.
Andere möchten vielleicht das Risiko für den Rest der Entwicklung reduzieren oder eine Plattform für längerfristige Kosteneinsparungen schaffen.
* Verschiedene Methoden kennen, um Werte auszudrücken, z.B. MoSCoW-Priorisierung, definierte Wertebereiche, lineare Sortierung aller Anforderungen, gewichtete Faktor-Methoden, Kosten der Verzögerung, ...


[[LG-6-2]]]
===== LG 6-2: Ordnen und Priorisieren nach Geschäftswert

* Kennen verschiedener Strategien für ordnen und priorisieren, z.B. gewichteter kürzester Job zuerst (WSJF), Risiko aufschieben, Risiko zuerst ...
* Wissen, wie man bei der Bestellung von Anforderungen mit Abhängigkeiten zwischen Anforderungen umgeht
* Mechanismen zur Aufteilung von Anforderungen kennen, um Abhängigkeiten zu vermeiden


===== LG 6-3: Schätzung des Bedarfs

* Verstehen der Notwendigkeit einer Bedarfsschätzung, auch als Indikator für die mögliche Verfeinerung und Zerlegung größerer Anforderungen, wenn diese noch nicht gut genug geschätzt werden können.
* Verstehen des Unterschieds zwischen absoluten Schätzungen (in Personentagen, Kosten, ...) und relativen Schätzungen (z.B. Story Points)
* Die Vor- und Nachteile von absoluten und relativen Schätzungen kennen
* einige relative Schätztechniken kennen wie T-Shirt-Größe, Planning Poker (mit Fibonacci-Werten)
* verschiedene Schätzverfahren kennen, z.B. Funktionspunkte, Story-Punkte, Affinitätsschätzung, _wall estimation_, etc.

// end::DE[]

// tag::EN[]

=== {learning-goals}

[[LG-6-1]]
==== LG 6-1: Understanding different kinds of business value

* Understand that different stakeholders may see different value in requirements.
Some of them may be interested in short turn revenue, others in improvement of customer satisfaction, or quick time-to-market.
Others might want to reduce the risk for the rest of the development, or create a platform for longer term cost savings.
* Know different methods for expressing value, e.g. MoSCoW-prioritization, defined ranges of values, linear sorting of all requirements, weighted factor methods, cost of delay, ...


[[LG-6-2]]
==== LG 6-2: Ordering requirements by business value

* Know different strategies for ordering and prioritization, e.g. weighted shortest job first (WSJF), defer risk, risk-first ...
* Know how to handle dependencies between requirements when ordering requirements
* Know mechanism to split requirements in order to avoid dependencies

[[LG-6-3]]
==== LG 6-3: Estimating requirements

* Understand the need for estimating requirements, also as an indicator to potentially refine and decompose larger requirements when they cannot be estimated well enough yet.
* Understand the difference between absolute estimates (in person days, costs, ...) versus relative estimates (e.g. story points)
* Know advantages and disadvantages of absolute and relative estimates
* Know some relative estimation techniques like T-Shirt-sizing, Planning Poker (with Fibonacci values)
* Know different estimation techniques, e.g. function points, story points, affinity estimation, wall estimation, etc.


// end::EN[]
