// (c) iSAQB e.V. (https://isaqb.org)
// ====================================================



// tag::DE[]
== Beispiel


|===
| Unterricht: 60 Min. | Übungen: keine
|===


In jeder lizenzierten Schulung muss mindestens ein Beispiel gut formulierter architekturrelevanter Anforderungen vorgestellt, diskutiert und bewertet werden.

Das Beispiel kann sich je nach Schulungsanbieter unterscheiden oder sich nach den Interessen der Teilnehmer:innen richten. Details des Beispiels werden daher vom iSAQB nicht vorgegeben.


=== {learning-goals}

[[LZ-10-1]]
==== LZ 10-1: Beispiele gut formulierter Anforderungen verschiedener Kategorien kennen

[[LZ-10-2]]
==== LZ 10-2: (Gegen-)Beispiele kennen, etwa mehrdeutige, inkonsistente und widersprüchliche Anforderungen verschiedener Kategorien

// end::DE[]

// tag::EN[]
== Example


|===
| Teaching: 60 min | Exercises: none
|===


Within each licensed training there must be at least one example of well written architecturally significant requirements presented, discussed and evaluated.

The example may differ for each training provider or depend on the interest of the participants. Therefore, details for the example are not specified by iSAQB.


=== {learning-goals}

[[LG-10-1]]
==== LG 10-1: Know examples of well-articulated requirements of various categories

[[LG-10-2]]
==== LG 10-2: Know (counter-)examples, like ambiguous, inconsistent and contradicting requirements of various categories



// end::EN[]
