// tag::FEEDBACK[]
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
=== {learning-goals}


[LG-5-1]]
===== LG 5-1: Anwendbarkeit und die Anwendungsbereiche für Behavior Driven Development (BDD) kennen

* Wissen, dass BDD aus Ansätzen und Technologien wie TDD (testgetriebene Entwicklung) und ATDD (akzeptanztestgetriebene Entwicklung) entstanden ist.
* wissen, dass es verschiedene Möglichkeiten gibt, die Anforderungen zu präzisieren
** Zustands- oder Tätigkeitsmodelle
** angesichts-dann-Szenarien
* wissen, dass BDD für ein breites Spektrum von IT-Systemtypen einsetzbar ist, z.B. Informationssysteme, Business Intelligence Systeme, mobile Anwendungen


===== LG 5-2: Prinzipien von Behavior Driven Development verstehen

* Wissen, dass BDD eine kollaborative Anforderungsermittlung ist, die Gespräche um konkrete Beispiele herum nutzt, um ein gemeinsames Verständnis der Anforderungen aufzubauen.
* Wissen, dass kollaborative Workshops und Diskussionsformate, wie z.B. Three Amigo Sessions (TAS), dabei helfen, korrekte Anforderungen zu erhalten.  In einem TAS arbeiten die drei Rollen "Product Owner" (oder Geschäftsanalyse), "Entwickler" und "Tester" bei der Ermittlung von Anforderungen zusammen.
* Wissen, dass konkrete Beispiele ein geeigneter Weg sind, um die Problemdomäne zu erkunden, und dass sie eine Grundlage für Akzeptanztests bieten. Example-Mapping hilft, Regeln zu finden, offene Fragen zu klären und neue Stories zu identifizieren.
* Wissen, dass BDD Benutzeranforderungen in Features erklärt, Features in Stories und die Stories in (ausführbare) Beispiele aufschlüsselt.


[[LG-5-3]]]
===== LG 5-3: Gherkin und Cucumber als Beispiel für BDD kennen

* Die `Given-When-Then (GWT) Syntax kennen, die Gherkin vorschlägt.
* Wissen, dass auf dem Prinzip "Given-When-Then" basierende Formulierungen von Anforderungen die Testautomatisierung erleichtern.
* Wissen, dass es verschiedene Werkzeuge gibt, um die Given-When-Then-Verhaltensspezifikationen auf den Quellcode des Systems abzubilden (z.B. Cucumber, RSpec, SpecFlow, GivWenZen).
* Optional: Beispiele von GWT-Spezifikationen kennen, mit dem entsprechenden Glue-Code zur automatischen Ausführung.

// end::DE[]

// tag::EN[]
=== {learning-goals}



[[LG-5-1]]
==== LG 5-1: Knowing about the applicability and application domains for Behavior Driven Development (BDD)

* Know that BDD originated from approaches and technologies like TDD (test-driven development) and ATDD (acceptance-test-driven development).
* Know that various options exist to add precision to requirements
** State models or activity models
** given-when-then scenarios
* Know that BDD is applicable for a broad range of IT-system types, e.g. information systems, business intelligence systems, mobile apps


[[LG-5-2]]
==== LG 5-2: Understanding principles of Behaviour-Driven Development (BDD)

* Know that BDD is a collaborative requirements discovery practice that uses conversations around concrete examples to build a shared understanding of requirements.
* Know that collaborative workshops and discussion formats, like Three Amigo Sessions (TAS), help in getting correct  requirements.  In a TAS, the three roles "product owner" (or business analyse), "developer" and "tester" collaborate in discovering requirements.
* Know that concrete examples are a suitable way to help explore the problem domain, and they provide a basis for acceptance tests. Example mapping helps to find rules, open questions and identify new stories.
* Know that BDD explains user requirements in features, breaks features down into stories and the the stories into to (executable) examples.


[[LG-5-3]]
==== LG 5-3: Knowing Gherkin and Cucumber as examples for BDD

* Know the `Given-When-Then (GWT) syntax as proposed by Gherkin.
* Know that Given-When-Then based formulations of requirements facilitate test automation.
* Know that several tools exist to map Given-When-Then behavior specifications to the systems' source code (e.g. Cucumber, RSpec, SpecFlow, GivWenZen).
* Optionally know examples of GWT specifications with the appropriate glue code for automatic execution.

// end::EN[]

