// (c) iSAQB e.V. (https://isaqb.org)
// ====================================================



// tag::DE[]
== Einführung und Motivation

Dieses Thema begründet, warum Architekturentscheidungen hinreichende Anforderungen als Grundlage benötigen.
Architekt:innen sollten wissen, dass sie diesen Input entweder von den für Requirements Engineering verantwortlichen Personen einfordern können oder die Anforderungen selbst ermitteln und verstehen müssen.

Es braucht jedoch keine _vollständigen_ Anforderungen, sondern nur die Teilmenge, die für Architekturentscheidungen notwendig ist (die sogenannten architekturrelevanten Anforderungen, engl. _architecturally significant requirements_).
Der Rest kann iterativ und inkrementell ermittelt werden, sodass er _just in time_ für Entscheidungen vorliegt.

include::01-duration-terms.adoc[{include_configuration}]
include::02-learning-goals.adoc[{include_configuration}]
// end::DE[]

// tag::EN[]
== Introduction and Motivation

This topic introduces the need for sufficient requirements as a basis for making architectural decisions.
Architects should be aware that they can either ask persons responsible for requirements engineering to deliver this input or they have to elicit and understand the requirements themselves.

However, there is no need for _complete_ requirements, only for the subset necessary to make architectural decisions (called architecturally significant requirements).
The rest can be elicited in an iterative and incremental manner, to be available _just in time_ for decision making.

include::01-duration-terms.adoc[{include_configuration}]
include::02-learning-goals.adoc[{include_configuration}]
// end::EN[]
