=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Die Notwendigkeit von Anforderungen als Entscheidungsgrundlage verstehen

* Wissen, warum gute Anforderungen – insbesondere Qualitätsanforderungen – aus Sicht der Softwarearchitektur notwendig sind
* Die Kernaufgaben von Softwarearchitekt:innen kennen, zu denen das Klären von Anforderungen und Randbedingungen gehört
* Verstehen, dass Architekt:innen vorab keine vollständigen Anforderungen benötigen, sondern sich auf architekturrelevante Anforderungen konzentrieren sollten <<toth>>

[[LZ-1-2]]
==== LZ 1-2: Verantwortlichkeiten, Rollen und Kernaktivitäten verstehen

* Wissen, dass es unterschiedliche Rollenbezeichnungen für die Verantwortlichen für Anforderungen gibt (Business Analyst, Requirements Engineer, Product Owner)
* Deren Beziehung zu Architekt:innen und Entwicklungsteams verstehen
* Kernaufgaben des Requirements Engineering kennen, darunter Ermittlung, Dokumentation, Prüfung und Pflege

[[LZ-1-3]]
==== LZ 1-3: Den inkrementellen Charakter der Anforderungsermittlung verstehen („Just in Time")

* Verstehen, dass Anforderungen und Architektur iterativ entwickelt werden können (und sollten)
* Verstehen, dass Architekt:innen keine „vollständigen" Anforderungen brauchen, sondern stets gerade genug Anforderungen, um Entwurfsentscheidungen für die nächsten Iterationen zu treffen
* Verstehen, dass Anforderungen iterativ und inkrementell ermittelt werden können

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understanding the need for requirements as basis for decision making

* Know the need for good requirements, especially quality requirements seen from the perspective of software architecture
* Know the key tasks for software architects which include clarifying requirements and constraints
* Understand that architects do not need complete requirements up-front, but should focus on architecturally significant requirement <<toth>>

[[LG-1-2]]
==== LG 1-2: Understanding responsibilities, roles and key activities

* Know that there are different job titles for persons responsible for requirements (Business Analysts, Requirements Engineers, Product Owner)
* Understand their relationship to architects and development teams.
* Know key tasks in requirements engineering, including elicitation, documentation, checking and maintenance

[[LG-1-3]]
==== LG 1-3: Understanding the incremental nature of requirements elicitation ("Just in Time")

* Understand that requirements and architecture can (and should) be developed iteratively
* Understand that architects do not need "complete" requirements, but always just enough requirements to make design decisions for the next iterations
* Understand that requirements can be elicitated iteratively and incrementally

// end::EN[]


