=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Die Notwendigkeit von Anforderungen als Entscheidungsgrundlage verstehen

* Wissen, warum gute Anforderungen – insbesondere Qualitätsanforderungen – aus Sicht der Softwarearchitektur notwendig sind
* Die Kernaufgaben von Softwarearchitekt:innen kennen, zu denen das Klären von Anforderungen und Randbedingungen gehört
* Das Konzept architekturrelevanter Anforderungen (ASR) kennen <<toth>>, siehe auch Just-in-Time-Anforderungen

[[LZ-1-2]]
==== LZ 1-2: Verantwortlichkeiten, Rollen und Kernaktivitäten verstehen

* Wissen, dass es unterschiedliche Rollenbezeichnungen für die Verantwortlichen für Anforderungen gibt (Business Analyst, Requirements Engineer, Product Owner)
* Deren Beziehung zu Architekt:innen und Entwicklungsteams verstehen
* Kernaufgaben des Requirements Engineering kennen, darunter Erhebung, Dokumentation, Prüfung und Pflege

[[LZ-1-3]]
==== LZ 1-3: Den inkrementellen Charakter der Anforderungserhebung verstehen („Just in Time")

* Verstehen, dass Anforderungen und Architektur iterativ entwickelt werden können (und sollten)
* Wissen, dass Architekt:innen zu jedem Zeitpunkt nur die Anforderungen brauchen, die für anstehende Entwurfsentscheidungen relevant sind (Just-in-Time-Anforderungen, siehe <<LZ-1-1>>)
* Verstehen, dass Anforderungen iterativ und inkrementell erhoben werden können

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understanding the need for requirements as basis for decision making

* Know the need for good requirements, especially quality requirements seen from the perspective of software architecture
* Know the key tasks for software architects which include clarifying requirements and constraints
* Know the concept of architecturally significant requirements (ASR) <<toth>>, see also Just-in-Time Requirements

[[LG-1-2]]
==== LG 1-2: Understanding responsibilities, roles and key activities

* Know that there are different job titles for persons responsible for requirements (Business Analysts, Requirements Engineers, Product Owner)
* Understand their relationship to architects and development teams.
* Know key tasks in requirements engineering, including elicitation, documentation, checking and maintenance

[[LG-1-3]]
==== LG 1-3: Understanding the incremental nature of requirements elicitation ("Just in Time")

* Understand that requirements and architecture can (and should) be developed iteratively
* Know that architects only need the requirements relevant for the design decisions at hand, at any point in time (Just-in-Time Requirements, see <<LG-1-1>>)
* Understand that requirements can be elicitated iteratively and incrementally

// end::EN[]


