

// tag::DE[]

|===
| Unterricht: 75 Min. | Übungen: 75 Min.
|===

Auch wenn Requirements Engineering heute iterativ und inkrementell erfolgen sollte, braucht es einige Vorab-Aktivitäten, die die detaillierte Anforderungserhebung und zentrale Architekturentscheidungen leiten.
Sie bilden den „Sauberen Start" (Clean Start) einer Projekt- oder Produktentwicklung.
Dazu gehören vor allem:

* Vision und Ziele definieren
* Stakeholder identifizieren
* Scope festlegen
* Nach dem Prinzip „Breite vor Tiefe" vorgehen, um frühe Priorisierung und Planung zu ermöglichen

=== Begriffe und Konzepte

Vision, Business Goals, Stakeholder, Scope, Kontext, SMART, PAM (Purpose, Advantage, Metric), Product Vision Box, Product Vision Canvas

// end::DE[]

// tag::EN[]

|===
| Teaching: 75 min | Exercises: 75 min
|===

Although requirements engineering today should be performed in an iterative, incremental way there is a need for some up-front activities to guide detailed requirements elicitation and key architectural decision making.
They are called a "clean start" for a project or product development.
These mainly include:

* Defining vision and goals
* Identifying stakeholders
* Setting the scope
* Applying a “breadth before depth” approach to allow for early prioritization and planning.

=== Terms and concepts

Vision, Business Goals, Stakeholders, Scope, Context, SMART, PAM (Purpose, Advantage, Metric), Product Vision Box, Product Vision Canvas

// end::EN[]


