=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Die Notwendigkeit einiger (begrenzter) Vorab-Aktivitäten verstehen

* Verstehen, dass auch bei iterativer Entwicklung einige Vorab-Aktivitäten notwendig sind
* Wissen, dass explizites Wissen über Visionen, Ziele und relevante Stakeholder erforderlich ist, damit das Entwicklungsteam fundierte Entscheidungen über die Architektur des Systems treffen kann
* Verstehen, dass eine Verständigung über Scope und Kontext erforderlich ist, insbesondere über die Schnittstellen zwischen Scope und Kontext (d.h. die externen Schnittstellen des Produkts)

[[LZ-3-2]]
==== LZ 3-2: Die Notwendigkeit von (übergeordneter) Vision und Business Goals verstehen

* Verstehen, dass Visionen oder Business Goals die obersten Anforderungen sind, also jene, die sich (hoffentlich) während eines Projekts nicht ändern <<pichler>>
* Verstehen, dass Visionen und Ziele quantifiziert und messbar gemacht werden sollten, um Erfolg in Bezug auf Business Value überprüfen zu können

[[LZ-3-3]]
==== LZ 3-3: Verschiedene Möglichkeiten und Notationen, Visionen und Business Goals auszudrücken

* Verschiedene Wege kennen, Vision und Ziele zu definieren (explizite Zielformulierungen, Value Propositions für unterschiedliche Stakeholder, Product Vision Box <<hohmann>>, Product Vision Canvas <<pichler-visionboard>>, „News from the Future")
* Merkhilfen (Mnemotechnik) für Vision- oder Zielformulierungen kennen (SMART, PAM)

[[LZ-3-4]]
==== LZ 3-4: Die Bedeutung unterschiedlicher Stakeholder und ihr Einfluss auf Produkt oder System

* Wissen, dass Stakeholder die wichtigsten Quellen für Anforderungen sind
* Verstehen, dass fehlende Stakeholder fehlende Anforderungen bedeuten können
* Verstehen, dass Stakeholder auf spezifische, angemessene Weise angesprochen werden müssen

[[LZ-3-5]]
==== LZ 3-5: Unterschiedliche Bedürfnisse und Werte verschiedener Stakeholder („Value Propositions")

Verstehen, dass verschiedene Stakeholder unterschiedliche Bedürfnisse haben und unterschiedlicher Meinung sein können, was an einem Produkt wertvoll ist.

Wissen, dass:

* auch die Entwickler:innen Stakeholder sind
* es etablierte Klassifikationsschemata für Stakeholder gibt (z. B. Stakeholder-Matrix)
* eine priorisierte Stakeholder-Liste hilft, Anforderungen nach Business Value zu priorisieren
* Architekt:innen Zielkonflikte zwischen den Bedürfnissen der Stakeholder behandeln müssen
* welche Stakeholder häufig vergessen werden (z. B. Legal, Betrieb, Support)

[[LZ-3-6]]
==== LZ 3-6: Scope festlegen und den Kontext des Systems abgrenzen

* Zwischen Business Scope und Produkt-Scope unterscheiden
* Die Bedeutung externer Schnittstellen kennen
* Verschiedene Ebenen von „extern" unterscheiden (extern zum System, extern zur Geschäftseinheit, extern zum Unternehmen)
* Verschiedene Möglichkeiten und Notationen kennen, Scope und Kontext auszudrücken, z.B. Kontextdiagramme

// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Understanding the need for some (limited) upfront activities

* Understand that even with iterative development some upfront activities are necessary.
* Know that explicit knowledge of visions, goals and relevant stakeholders is required so that the development team can take informed decisions about the system's architecture.
* Understand that an agreement about scope and context is required, especially about the interfaces between scope and context (i.e. the external interfaces of the product).

[[LG-3-2]]
==== LG 3-2: Understanding the need for (high level) vision and business goals

* Understand that visions or business goals are your highest level requirements, i.e. those requirements that are (hopefully) not changed during a project <<pichler>>
* Understand that visions and goals should be quantified and made measurable to be able to check success in terms of business value.

[[LG-3-3]]
==== LG 3-3: Different options and notations for expressing visions and business goals

* Know various ways to define vision and goals (explicit goal statements, value propositions for different stakeholders, Product Vision Box <<hohmann>>, Product Vision Canvas <<pichler-visionboard>>, "news from the future")
* Know mnemonics for vision or business goal statements (SMART, PAM)

[[LG-3-4]]
==== LG 3-4: The importance of different stakeholders and their influence on the product or system

* Know that stakeholders are the most important sources of requirements.
* Understand that missing stakeholders may mean missing requirements.
* Understand that architects should be aware that stakeholders need to be addressed in specific, adequate ways.

[[LG-3-5]]
==== LG 3-5: Different needs and values of different stakeholders  ("value propositions")

Understand that different stakeholders will have different needs and may differ in their opinions what is valuable in a product

Know:

* that the developers are also stakeholders
* that there are established classification schemes for stakeholders (e.g. Stakeholder Matrix)
* that a prioritized stakeholder list helps to prioritize requirements by business value
* architects have to handle goal conflicts between stakeholder's needs
* about commonly forgotten stakeholders (e.g. legal, operations, support)

[[LG-3-6]]
==== LG 3-6: Scoping and delimiting the context of the system

* Distinguish between business and product scope
* Know about the importance of external interfaces
* Distinguish between various levels of externality (external to the system, external to the business unit, external to the enterprise)
* Know different options and notations for expressing scope and context, i.e. context diagrams

// end::EN[]


