


// tag::DE[]

=== Was vermittelt das Modul {curriculum-short}?

Architekt:innen und Entwicklungsteams erhalten oft nur mittelmäßige Anforderungen als Input für ihre Arbeit.
Ziel dieses Moduls ist es, Architekt:innen mit genügend Anforderungs-Know-how auszustatten, sodass sie fundierte Architekturentscheidungen treffen können – basierend auf den tatsächlichen Bedürfnissen der Stakeholder.
Sie sollten entweder wissen, wie man Anforderungen ermittelt (in agilen und iterativen Vorgehensweisen), oder zumindest wissen, was sie von anderen in ihrem Umfeld einfordern müssen.


// end::DE[]

// tag::EN[]

=== What does the module {curriculum-short} convey?

Architects and development teams often get only mediocre requirements as input for their work.
The goal of this module is to equip architects with enough requirements know-how, so that they can take educated architecture decisions, based on the real needs of stakeholders.
They should either know how to elicit requirements (in agile and iterative approaches) or - at least - to know what to ask from others in their environment.


// end::EN[]

