
// tag::DE[]
=== Ergänzende Informationen, Begriffe, Übersetzungen

Soweit für das Verständnis des Lehrplans erforderlich, haben wir Fachbegriffe ins https://github.com/isaqb-org/glossary[iSAQB-Glossar] aufgenommen, definiert und bei Bedarf durch die Übersetzungen der Originalliteratur ergänzt.

=== Helfen Sie uns, diesen Lehrplan zu verbessern

Sie finden die neueste Version dieses Dokuments online (https://isaqb-org.github.io/curriculum-req4arc/),
wo Sie gerne Feedback und Verbesserungsvorschläge geben können.
// end::DE[]

// tag::EN[]
[discrete]
=== Further information and terminology

To the extent necessary for understanding the curriculum, we have added definitions of required and important terms at the end of this document and to the https://github.com/isaqb-org/glossary[iSAQB glossary].

[discrete]
=== Help us improve this curriculum

You find the most recent version of this document online (https://isaqb-org.github.io/curriculum-req4arc/), where you are encouraged to provide feedback.
// end::EN[]

// tag::REMARK[]
// end::REMARK[]
