

// tag::DE[]

// end::DE[]

// tag::EN[]
[width=50%]
|===
| Teaching: 120 min | Exercises: 90 min
|===

This topic deals with the kinds of requirements that are often more important for architects than functional requirements: quality requirements and constraints. These two categories are often called non-functional requirements, although we recommend to avoid this term.
Categorization schemata for quality requirements and constraints are discussed, as well as notations to capture them.

Similar to functional requirements qualities and constraints are often very vague at the beginning. Architect learn how to refine them, or how to derive functional requirements from qualities in order to make them more precise.
Also quality requirements can be made more precise using scenario-based approaches.
Last but not least: also quality requirements have to be made checkable by adding acceptance criteria to them.

=== Terms and concepts

Quality Requirement, Constraint, Non-functional Requirement

// end::EN[]

// tag::REMARK[]
// end::REMARK[]

