// tag::FEEDBACK[]
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]

=== {learning-goals}

[[LG-4-1]]
===== LG 4-1: Den Unterschied zwischen Qualitätsanforderungen und anderen Anforderungen verstehen

* Eine Definition von Qualitätsanforderungen und Randbedingungen kennen
* Wissen, dass die Grenze zwischen funktionalen Anforderungen und Qualitätsanforderungen unscharf ist, da Qualitäten manchmal durch die Umwandlung in Funktionen präzisiert werden.

[[LG-4-2]]
===== LG 4-2: Kategorien von Qualitätsanforderungen und Randbedingungen verstehen

* Checklisten für Qualitätsanforderungen und Qualitätsstandards kennen (z.B. ISO 25010, VOLERE, ...)
* Kategorien von Randbedingungen kennen (organisatorische Randbedingungen, technische Randbedingungen, ...)
* Verstehen, dass Architekten nicht alle Qualitätsanforderungen und Randbedingungen in einem frühen Stadium der Entwicklung benötigen, sondern die wichtigsten finden sollten, da sie die treibenden Kräfte für Architekturentscheidungen sind.

[[LG-4-3]]
===== LG 4-3: Erheben und Spezifizieren von Qualitätsanforderungen

* Wissen, wie man Qualitätsanforderungen durch Szenarien oder textuell spezifiziert, einschließlich der Motivation ("Warum?")
* Mit Hilfe von Checklisten und Kategorisierungsschemata die wichtigsten Kandidaten von Qualitätsanforderungen finden
* Wissen, dass unterschiedliche Arten der Erhebung und Spezifikation von Qualitätsanforderungen schnellere oder langsamere Ergebnisse mit verschiedenen Stakeholdern erzielen können.
Sie sollten die effizientesten Wege kennen, die von den Fähigkeiten, der Motivation und der Zeit ihrer Stakeholder abhängen.


[[LG-4-4]]
===== LG 4-4: Qualitätsanforderungen verfeinern

* Wissen, dass Qualitätsanforderungen oft vage beginnen.
Architekten haben verschiedene Möglichkeiten, um diese zu präzisieren.
** sie könnten entweder Unterkategorien der Kategorisierungsschemata verwenden (z.B. Benutzerfreundlichkeit = Leichte Bedienbarkeit und Leichte Erlernbarkeit)
** sie könnten Szenarien finden, um die beabsichtigte Bedeutung genauer auszudrücken, oder
** sie könnten funktionale Anforderungen vorschlagen, die die Intention der Qualitätsanforderung erfüllen (z.B. ein Rollenkonzept und die Verwendung von Passwörtern zur Umsetzung einer Sicherheitsanforderung vorschlagen)
* Wissen dass man Qualitätsbäume nach <<ATAM>> zur Verfeinerung der Qualitätsanforderungen einsetzen kann.

[[LG-4-5]]
===== LG 4-5: Festlegung von Akzeptanzkriterien für Qualitätsanforderungen

* Wissen, dass auch Qualitätsanforderungen Akzeptanzkriterien benötigen
* Wissen, dass die Akzeptanzkriterien für Qualitätsanforderungen oft durch die Angabe von Toleranzen oder Schwellwerten oder durch die Zulassung von Abweichungen für bestimmte Interessengruppen festgelegt werden können (z.B. Personen, die kein Englisch sprechen, erhalten 20% mehr Zeit, um ein Ergebnis zu erzielen)


[[LG-4-6]]
===== LG 4-6: Priorisierung der Qualitätsanforderungen

* Wissen, dass Architekten Qualitätsanforderungen in zwei Dimensionen priorisieren sollten: Geschäftswert und technische Herausforderungen
* Wissen, dass hauptsächlich Anforderungen mit hohem Geschäftswert und großen technischen Herausforderungen frühzeitig bei Architekturentscheidungen berücksichtigt werden sollten

[[LG-4-7]]
===== LG 4-7: Pragmatische Alternativen zu detaillierten Akzeptanzkriterien

* Wissen, dass es bei einigen Qualitätsanforderungen schwierig ist, ihre Erfüllung direkt nach der Implementierung zu überprüfen.
Eine andere Möglichkeit, solche Eigenschaften zu überprüfen, ist die statistische Beobachtung über die Zeit ("schaue, ob die Anforderung erfüllt ist") anstelle von quantifizierten Akzeptanzkriterien.
* Wissen, dass bei UI-Anforderungen z.B. mit Hilfe von Nutzungsanalysen überprüft werden kann, ob sie ausreichend gut umgesetzt sind.


// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-4-1]]
==== LG 4-1: Understanding the difference between quality and other requirements

* Know a definition of quality requirements and constraints
* Know that there is a very thin borderline between functional requirements and quality requirements, since qualities are sometimes made more precise by transforming them into functions.

[[LG-4-2]]
==== LG 4-2: Understanding categories of qualities and constraints

* Know checklists for quality requirements, quality standards (e.g. ISO 25010, VOLERE, ...)
* Know categories of constraints (organizational constraints, technical constraints, …)
* Understand that architects don't need all quality requirements and constraints early in the project, but have to find the most important ones, since they are architecture drivers and will influence very important architectural decision

[[LG-4-3]]
==== LG 4-3: Eliciting and specifying quality requirements

* Knowing how to specify qualities by scenarios or textual specifications, including motivation ("why?")
* Using checklists and categorization schemes to find the most important candidates of quality requirements
* Know that architects should be aware that different styles of eliciting and specifying qualities can achieve quicker or slower results with different stakeholders.
They should know the most efficient ways depending on skills, motivation and time of their stakeholders.


[[LG-4-4]]
==== LG 4-4: Refining quality requirements

* Know that quality requirements often start vague.
Architects have various ways of adding precision
** they could either use subcategories of the categorization schemes (user friendliness = ease of use and ease of learning)
** they could find scenarios to express the intended meaning more precisely, or
** they could suggest functional requirements that fulfil the intend of the quality requirement (e.g. suggest a role concept and the use of passwords to implement a security requirement)
* Know the quality trees <<ATAM>> can be used to refine quality requirements

[[LG-4-5]]
==== LG 4-5: Specifying acceptance criteria for quality requirements

* Know that also quality requirements need acceptance criteria
* Know that acceptance criteria for quality requirements can often be specified by giving tolerances or thresholds, or allowing deviations for certain stakeholders (e.g. person who do not speak English are given 20% more time to achieve a result)


[[LG-4-6]]
==== LG 4-6: Prioritizing quality requirements

* Know that architects should prioritize quality requirements in two dimensions: business value and technical challenge
* Know that mainly requirements with high business value and big technical challenge should be considered early on for architectural decisions

[[LG-4-07]]
==== LG 4-7: Pragmatic alternatives to detailed acceptance criteria

* Know that for some qualities it is hard to check their fulfilment right after implementation.
Another way to check such qualities is statistical observation over time ("see if requirement is met") instead of quantified acceptance criteria.
* Know that for UI-requirements e.g. usage-analytics can be used to check whether they are sufficiently well implemented.


// end::EN[]
