

// tag::DE[]

|===
| Unterricht: 90 Min. | Übungen: 90 Min.
|===

Dieses Thema behandelt die Arten von Anforderungen, die für Architekt:innen oft wichtiger sind als funktionale Anforderungen: Qualitätsanforderungen und Randbedingungen. Diese beiden Kategorien werden oft als nichtfunktionale Anforderungen bezeichnet – ein Begriff, den wir zu vermeiden empfehlen.
Kategorisierungsschemata für Qualitätsanforderungen und Randbedingungen werden ebenso diskutiert wie Notationen, um sie festzuhalten.

Ähnlich wie funktionale Anforderungen sind Qualitäten und Randbedingungen anfangs oft sehr vage. Architekt:innen lernen, sie zu verfeinern oder funktionale Anforderungen aus Qualitäten abzuleiten, um sie zu präzisieren.
Auch Qualitätsanforderungen lassen sich mit szenariobasierten Ansätzen präzisieren.
Nicht zuletzt müssen auch Qualitätsanforderungen durch Akzeptanzkriterien überprüfbar gemacht werden.

=== Begriffe und Konzepte

Qualitätsanforderung, Randbedingung (Constraint), nichtfunktionale Anforderung, Q42

// end::DE[]

// tag::EN[]

|===
| Teaching: 90 min | Exercises: 90 min
|===

This topic deals with the kinds of requirements that are often more important for architects than functional requirements: quality requirements and constraints. These two categories are often called non-functional requirements, although we recommend to avoid this term.
Categorization schemata for quality requirements and constraints are discussed, as well as notations to capture them.

Similar to functional requirements qualities and constraints are often very vague at the beginning. Architect learn how to refine them, or how to derive functional requirements from qualities in order to make them more precise.
Also quality requirements can be made more precise using scenario-based approaches.
Last but not least: also quality requirements have to be made checkable by adding acceptance criteria to them.

=== Terms and concepts

Quality Requirement, Constraint, Non-functional Requirement, Q42

// end::EN[]


