

// tag::DE[]
=== {learning-goals}

[[LZ-5-1]]
==== LZ 5-1: Den Unterschied zwischen Qualitäts- und anderen Anforderungen verstehen

* Eine Definition von Qualitätsanforderungen und Randbedingungen kennen
* Wissen, dass die Grenze zwischen funktionalen Anforderungen und Qualitätsanforderungen sehr schmal ist, da Qualitäten manchmal präzisiert werden, indem man sie in Funktionen überführt

[[LZ-5-2]]
==== LZ 5-2: Kategorien von Qualitäten und Randbedingungen verstehen

* Checklisten für Qualitätsanforderungen und Qualitätsstandards kennen (z.B. <<Q42>>, <<iso25010>>, Volere (siehe <<robertson-24>>), ...)
* Kategorien von Randbedingungen kennen (organisatorische Randbedingungen, technische Randbedingungen, ...)
* Verstehen, dass Architekt:innen nicht alle Qualitätsanforderungen und Randbedingungen früh im Projekt benötigen, aber die wichtigsten finden müssen, da diese Architekturtreiber sind und sehr wichtige Architekturentscheidungen beeinflussen

[[LZ-5-3]]
==== LZ 5-3: Qualitätsanforderungen ermitteln und spezifizieren

* Wissen, wie Qualitätsszenarien oder textuelle Spezifikationen inklusive Motivation („warum?") spezifiziert werden
* Checklisten und Kategorisierungsschemata nutzen, um die wichtigsten Kandidaten für Qualitätsanforderungen zu finden
* Wissen, dass unterschiedliche Stile der Ermittlung und Spezifikation von Qualitäten bei verschiedenen Stakeholdern schneller oder langsamer zu Ergebnissen führen können.
Architekt:innen sollten die effizientesten Wege kennen – abhängig von Fähigkeiten, Motivation und Zeit ihrer Stakeholder.


[[LZ-5-4]]
==== LZ 5-4: Qualitätsanforderungen verfeinern

* Wissen, dass Qualitätsanforderungen oft vage beginnen.
Architekt:innen haben verschiedene Möglichkeiten, sie zu präzisieren:
** Unterkategorien der Kategorisierungsschemata nutzen (Benutzerfreundlichkeit = leichte Bedienbarkeit und leichte Erlernbarkeit)
** Szenarien finden, die die beabsichtigte Bedeutung präziser ausdrücken, oder
** funktionale Anforderungen vorschlagen, die die Absicht der Qualitätsanforderung erfüllen (z.B. ein Rollenkonzept und Passwörter vorschlagen, um eine Sicherheitsanforderung umzusetzen)
* Wissen, dass Qualitätsbäume <<ATAM>> zur Verfeinerung von Qualitätsanforderungen genutzt werden können
* Wissen, dass das Q42-Qualitätsmodell <<Q42>> praktische Anleitung und pragmatische Beispiele für die Verfeinerung von Qualitätsanforderungen bietet

[[LZ-5-5]]
==== LZ 5-5: Akzeptanzkriterien für Qualitätsanforderungen spezifizieren

* Wissen, dass auch Qualitätsanforderungen Akzeptanzkriterien brauchen
* Wissen, dass Akzeptanzkriterien für Qualitätsanforderungen oft über Toleranzen oder Schwellwerte spezifiziert werden können, oder indem Abweichungen für bestimmte Stakeholder erlaubt werden (z.B. erhalten Personen, die kein Englisch sprechen, 20% mehr Zeit für ein Ergebnis)
* Quellen für Beispiele solcher Akzeptanzkriterien kennen, etwa Q42


[[LZ-5-6]]
==== LZ 5-6: Qualitätsanforderungen priorisieren

* Wissen, dass Architekt:innen Szenarien für Qualitätsanforderungen in zwei Dimensionen priorisieren sollten: Business Value und technische Herausforderung
* Wissen, dass nur Anforderungen mit hohem Business Value und großer technischer Herausforderung früh für Architekturentscheidungen berücksichtigt werden sollten

[[LZ-5-7]]
==== LZ 5-7: Pragmatische Alternativen zu detaillierten Akzeptanzkriterien

* Wissen, dass sich die Erfüllung mancher Qualitäten direkt nach der Implementierung nur schwer überprüfen lässt.
Ein anderer Weg ist die statistische Beobachtung über die Zeit („schauen, ob die Anforderung erfüllt ist") statt quantifizierter Akzeptanzkriterien.
* Wissen, dass sich z.B. bei UI-Anforderungen Usage Analytics einsetzen lassen, um zu prüfen, ob sie hinreichend gut umgesetzt sind

// end::DE[]

// tag::EN[]
=== {learning-goals}

[[LG-5-1]]
==== LG 5-1: Understanding the difference between quality and other requirements

* Know a definition of quality requirements and constraints
* Know that there is a very thin borderline between functional requirements and quality requirements, since qualities are sometimes made more precise by transforming them into functions.

[[LG-5-2]]
==== LG 5-2: Understanding categories of qualities and constraints

* Know checklists for quality requirements, quality standards (e.g. <<Q42>>, <<iso25010>>, Volere (see <<robertson-24>>), ...)
* Know categories of constraints (organizational constraints, technical constraints, …)
* Understand that architects don't need all quality requirements and constraints early in the project, but have to find the most important ones, since they are architecture drivers and will influence very important architectural decision

[[LG-5-3]]
==== LG 5-3: Eliciting and specifying quality requirements

* Knowing how to specify quality scenarios or textual specifications, including motivation ("why?")
* Using checklists and categorization schemes to find the most important candidates of quality requirements
* Know that architects should be aware that different styles of eliciting and specifying qualities can achieve quicker or slower results with different stakeholders.
They should know the most efficient ways depending on skills, motivation and time of their stakeholders.


[[LG-5-4]]
==== LG 5-4: Refining quality requirements

* Know that quality requirements often start vague.
Architects have various ways of adding precision
** they could either use subcategories of the categorization schemes (user friendliness = ease of use and ease of learning)
** they could find scenarios to express the intended meaning more precisely, or
** they could suggest functional requirements that fulfil the intend of the quality requirement (i.e. suggest a role concept and the use of passwords to implement a security requirement)
* Know the quality trees <<ATAM>> can be used to refine quality requirements
* Know that the Q42 quality model <<Q42>> provides practical guidance and pragmatic examples for refining quality requirements

[[LG-5-5]]
==== LG 5-5: Specifying acceptance criteria for quality requirements

* Know that also quality requirements need acceptance criteria
* Know that acceptance criteria for quality requirements can often be specified by giving tolerances or thresholds, or allowing deviations for certain stakeholders (i.e. person who do not speak English are given 20% more time to achieve a result)
* Know sources for examples of such acceptance criteria, like Q42


[[LG-5-6]]
==== LG 5-6: Prioritizing quality requirements

* Know that architects should prioritize scenarios for quality requirements in two dimensions: business value and technical challenge
* Know that only requirements with high business value and big technical challenge should be considered early on for architectural decisions

[[LG-5-7]]
==== LG 5-7: Pragmatic alternatives to detailed acceptance criteria

* Know that for some qualities it is hard to check their fulfilment right after implementation.
Another way to check such qualities is statistical observation over time ("see if requirement is met") instead of quantified acceptance criteria.
* Know that for UI-requirements e.g. usage-analytics can be used to check whether they are sufficiently well implemented.


// end::EN[]
