

// tag::DE[]
// end::DE[]

// tag::EN[]

|===
| Teaching: 75 min | Exercises: none
|===

In contrast to the waterfall model with explicit phases for requirements engineering and system/software architecture development all modern methods strive for a very close cooperation between architects and any role that is responsible for requirements engineering.
Examples for such processes include design thinking (<<gerstbach>>), lean startup (<<ries>>), design sprints (<<banfield>>) and many of the scaling frameworks in the agile world.

Architects should also understand different ways to capture and document requirements, from managing a product backlog to creating requirements documents - and the relationship of such requirements documents to architecture documentation.

=== Terms and concepts

Design Thinking (<<gerstbach>>), Design Sprint (<<banfield>>), Lean Startup (<<ries>>), Three Amigo Sessions (<<dinwiddie>>), Twin Peaks Model (<<nuseibeh>>), Discover-to-Deliver (<<gottesdiener-12>>), Requirements Documentation, Traceability


// end::EN[]


