// tag::FEEDBACK[]
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
=== {learning-goals}

[LG-7-1]]
===== LG 7-1: Verstehen der Zusammenarbeit zwischen Architekten und anderen Rollen bezüglich der Anforderungen

* Verstehen, dass die iterative Systementwicklung alle am Entwicklungsprozess beteiligten Rollen umfasst
* Wissen, dass Architekten ständig mit Business-Analysten und Anforderungsmanagern, sowie Entwicklern und Testern interagieren

===== LG 7-2: Kooperative Ansätze in der Produktentwicklung kennen

* Die Grundideen kooperativer Ansätze kennen wie _Discover to Deliver_ <<Gottesdiener-12>>, Design Thinking <<<gerstbach>>, Lean Startup <<ries>>, Design Sprints <<Banfield>>
* Verstehen Sie, wie solche iterativen Ansätze auf größere Systeme, die mehr als ein Entwicklungsteam umfassen, skaliert werden können, die möglicherweise geografisch verteilt sind.


[[LG-7-3]]
===== LG 7-3: Anforderungsdokumentation verstehen

* Wissen, dass in formelleren Situationen schriftliche Anforderungsspezifikationen unerlässlich sind
* Wissen, dass mündliche Kommunikation (_Reden und Diskutieren_) oft effektiver ist als schriftliche
* Verstehen der Balance zwischen Schreiben und Sprechen (Pflichtenheft versus Geschichtenkarten)


===== LG 7-4: Verstehen der Rückverfolgbarkeit von Anforderungen zu anderen Artefakten

* Wissen, was Anforderungen an Architektur, Quellcode, Test, technische Dokumentation _nachverfolgen_ bedeutet
* Verstehen Sie, dass die Verfolgung von Anforderungen zeitaufwendig ist und eine geeignete Werkzeugunterstützung erfordert
* Verstehen Sie, dass die Rückverfolgung von Anforderungen manchmal obligatorisch ist, z.B. bei sicherheitskritischen Systemen.  

// end::DE[]

// tag::EN[]

=== {learning-goals}

[[LG-7-1]]
==== LG 7-1: Understand the cooperation between architects and other roles concerning requirements

* Understand that iterative system development includes all roles involved in the development process
* Know that architects constantly interact with business analysts and requirements persons, as well as developers and testers

[[LG-7-2]]
==== LG 7-2: Know cooperative approaches to product development

* Know the basic ideas of cooperative approaches like _Discover to Deliver_ <<Gottesdiener-12>>, Design Thinking <<gerstbach>>, Lean Startup <<ries>>, Design Sprints <<Banfield>>
* Understand how such iterative approaches can be scaled to larger systems, that involve more than one development team, potentially geographically distributed.


[[LG-7-3]]
==== LG 7-3: Understand requirements documentation

* Know that in more formal situations written requirements specifications are essential
* Know that oral communication (_talking and discussing_) is often more effective than writing
* Understand the balance between writing and talking (requirements specification versus story cards)


[[LG-7-4]]
==== LG 7-4: Understand traceability from requirements to other artifacts

* Know what requirements _tracing_ to architecture, source code, test, technical documentation means
* Understand that requirements tracing is time-consuming and requires appropriate tool support
* Understand that requirements tracing is sometimes mandatory, e.g. for safety-critical systems.  

// end::EN[]
